Repository rainlab/blog-plugin, pull requests merged in 2019-05, with the labels that each got.

#434 Show real posts count from nested categories in Categories component
  components/Categories.php
  models/Category.php
Labels: Status: Completed, Type: Maintenance

#436 Handle URL switching in Post component when using locale switcher
  components/Post.php
Labels: Status: Testing Needed, Type: Maintenance

#438 Handle non-existent posts
  components/Post.php
Labels: Status: Completed, Type: Enhancement

#394 Feature/#392 - Override default slug param name with custom ones
  classes/ComponentAbstract.php
  components/Categories.php
  components/Post.php
  components/Posts.php
  components/RssFeed.php
  models/Category.php
  models/Post.php
Labels: Status: Completed, Type: Maintenance

#443 Changed !== null to !empty
  models/Post.php
Labels: Type: Maintenance
